version: "2.1"
services:
  postgres:
    image: postgis/postgis:13-master
    env_file:
      .env
    ports:
      - "15433:5432"
    volumes:
      - $PWD/versions/2.6.1/DockerCompose/postgres/data:/var/lib/postgresql/data
      - $PWD/versions/2.6.1/DockerCompose/postgres/init:/docker-entrypoint-initdb.d
    container_name: postgres
    hostname: postgres
    networks:
      - airflow
  pgadmin:
    image: dpage/pgadmin4
    env_file:
      .env
    volumes:
      - $PWD/versions/2.6.1/DockerCompose/pgadmin:/var/lib/pgadmin
    ports:
      - "16544:80"
    depends_on:
      - postgres
    container_name: pgadmin
    networks:
      - airflow
  webserver:
    build: 
      context: $HOME/public/airflow/versions/2.6.1/Docker
    user: airflow
    hostname: webserver
    restart: always
    container_name: airflow
    env_file:
      .env
    volumes:
      - $PWD/versions/2.6.1/DockerCompose/dags:/opt/airflow/dags
      - $PWD/versions/2.6.1/DockerCompose/logs:/opt/airflow/logs
    ports:
      - "8089:8080"
    networks:
      - airflow
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 32
    depends_on:
      - postgres

networks:
  airflow:
    driver: bridge